name: Publish the website

on:
    push:
        branches: [master]
    release:
        types: [created]

jobs:
    publish-website:
        runs-on: ubuntu-latest
        name: Build and publish
        steps:
            -   uses: actions/checkout@v4
                with:
                    persist-credentials: false

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: "8.1"
                    ini-values: "phar.readonly=0"

            -   name: Build the website
                run: make package-devkit website

            -   name: Publish the website
                uses: JamesIves/github-pages-deploy-action@v4
                with:
                    ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
                    BRANCH: gh-pages
                    FOLDER: build/website
